### ISSUE TITLE
Recording fails after certain period of time

### ISSUE THREAD

**Issue by petrdvorak** [ggerganov/ggwave-objc#4]
When working with the application and the latest version 0.4.0, the capture of the recorded data fails. The first 2-3 captures work as expected, additional captures are ignored. With 0.2.0, the issue cannot be reproduced.

**Comment by ggerganov** [comment]
Thanks for reporting this! I forgot to update this repo when I published ggwave 0.4.0

There are some breaking changes in 0.4.0 C API that I believe could be causing this issue. Will need to take a more detailed look to see what is going on. Will merge #3 when I find the issue.

It's likely related to [ggwave_encode](https://github.com/ggerganov/ggwave/blob/a29fb485e11090ded753f8efd3b97e075d17802e/include/ggwave/ggwave.h#L188) now returning the number of bytes instead of the number of samples, or [ggwave_decode](https://github.com/ggerganov/ggwave/blob/a29fb485e11090ded753f8efd3b97e075d17802e/include/ggwave/ggwave.h#L259-L262) result no longer being NULL terminated.

**Comment by ggerganov** [comment]
@petrdvorak I think I have fixed the issue. Try using latest `master` and let me know if the problem persists.

**Comment by petrdvorak** [comment]
Seems to work OK, thank you for the fix! 👍
